### ISSUE TITLE
TypeError: Illegal invocation

### ISSUE THREAD

**Issue by HackerYunen** [Alanhays/facelessJsvmp#1]
在ServiceWorker 环境中，使用 ImportScript 和 self 关键字会出现非法反射问题，该如何解决呀，求大佬解答~

```
(function () {
    // src/events/install.js
    var install_default = function install_default() {
        self.addEventListener("install", function (event) {
            self.skipWaiting();
        });
    };
    install_default();
})
```

还有ImportScript 关键字没有被识别成系统关键字，会被从scope中通过.apply方式调用

**Comment by Alanhays** [comment]
你好，你所遇到的问题和你无关，是由于项目并不完善导致的。此项目是我学习jsvmp反编译而写的项目，暂时没有实现全部js语法的计划。如果您想加固js代码可以尝试 https://jsvmp.net/ 它是一个成熟的商业化产品，也可以试试开源的 https://github.com/2833844911/cy_jsvmp 和 https://jsvmp.com/CN/index.html。
